# Site/SEO settings
email: hello@aramboa.com 
baseurl: ""
permalink: /:year/:month/:dy/:title/
google_analytics: 

name: Aramboa
title: ARAMBOA
description: >
  This is Aramboa`s mind. Discover a collection of selected works on the edge of nature and culture. 
url: http://<Aramboa>.io
twitter_username: thomasvaeth
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/thomasvaeth
  - name: instagram
    url: https://www.instagram.com/aramboamusic/
  - name: linkedin
    url: https://www.linkedin.com/in/thomasvaeth/
  - name: github
    url: https://github.com/samesies
  - name: codepen
    url: https://codepen.io/thomasvaeth/

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Aramboa
    bio: Aramboa is the alias of Vienna-based producer Moritz René Scharf. Being involved in music since his early childhood coming from a jazz background on guitar, he started producing and performing electronic music quickly. After a first release experimenting on the edge of electronica/downtempo, shaped by lively collaborations, especially with singer Elena Shirin, international festival appearances in Europe, the U.S. and South-Africa followed. Now he is off for presenting his latest studio-works where dreamy/artificial soundscapes and a catchy live brass-section collide into a beatdriven euphoric dancefloor experience.
    url: https://www.instagram.com/aramboamusic/

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
